# Generated by Django 4.0.4 on 2022-05-30 13:43

from os import name
from django.db import migrations


def create_data(apps, schema_editor):

    Student = apps.get_model('students', 'Student')
    Student(name='Akash Ambani', email='akash@gmail.com', document='100000', phone='1234567890').save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
